name: 'Release'

on:
  workflow_dispatch:
    inputs:
      prerelease:
        default: true
        description: Is this a pre-release version?
        required: true
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          release-count: '1'
          skip-version-file: 'true'
          skip-commit: 'true'
          skip-pull: 'true'
          git-push: 'false'
          git-path: ". '!:labsdk'"
          tag-prefix: 'v'
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: Build project
        run: |
          make docker-build VERSION=${{ steps.version.outputs.version }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images
        run: |
          docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Update changelog
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          touch CHANGELOG.md
          echo -e "{{ steps.version.outputs.changelog }}\n\n$(cat CHANGELOG.md)" > CHANGELOG.md

          git add CHANGELOG.md
          git commit -m "chore(release): ${{ steps.version.outputs.version }}" CHANGELOG.md
          git push
      - name: Tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.tag }}',
              sha: context.sha
            })
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          body: |
            ${{ steps.version.outputs.clean_changelog }}
          prerelease: ${{ inputs.prerelease }}
          name: Version ${{ steps.version.outputs.version }}
          generate_release_notes: false
